#!/bin/bash -ex

source /usr/local/src/gitlab.conf

cat "########################################" > /home/log.txt
cat "########################################" > /home/log.txt
cat "########################################" > /home/log.txt
cat "############### 10ruby #################" > /home/log.txt
cat "########################################" > /home/log.txt
cat "########################################" > /home/log.txt
cat "########################################" > /home/log.txt


# update ruby
mkdir /tmp/ruby && cd /tmp/ruby
curl --remote-name --progress https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.6.tar.gz
echo '4e6a0f828819e15d274ae58485585fc8b7caace0  ruby-2.3.6.tar.gz' | shasum -c - && \
 tar xzf ruby-2.3.6.tar.gz
cd ruby-2.3.6
./configure --disable-install-rdoc
make
make install


# install re2
# git clone https://code.googlesource.com/re2
# cd re2
# make
# make test
# make install


# install gems
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
gem install bundler --no-ri --no-rdoc
# --version '1.14.6' 
gem install charlock_holmes --version $VERSION_CHARLOCK_HOLMES
unset HTTP_PROXY


