#!/bin/bash -ex

source /usr/local/src/gitlab.conf

echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "############ 05git2.16 #################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


# install/update git
cd /tmp
# curl --remote-name --progress https://www.kernel.org/pub/software/scm/git/git-2.16.2.tar.gz

echo "deb http://ftp.us.debian.org/debian testing main contrib non-free" >> /etc/apt/sources.list 
apt-get update
apt-get install -y git
apt-get clean all

# curl --remote-name --progress http://192.168.200.143/_removeit/git-2.16.2.tar.gz
# echo '9acc4339b7a2ab484eea69d705923271682b7058015219cf5a7e6ed8dee5b5fb  git-2.16.2.tar.gz' | shasum -a256 -c - && \
#  tar -xzf git-2.16.2.tar.gz
# cd git-2.16.2/
# ./configure
# make prefix=/usr/local all
# sudo make prefix=/usr/local install


echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "############### 10ruby #################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


# update ruby

apt-get install -y ruby
apt-get clean all

# mkdir /tmp/ruby && cd /tmp/ruby
# curl --remote-name --progress https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.6.tar.gz
# curl --remote-name --progress http://192.168.200.143/_removeit/ruby-2.3.6.tar.gz
# echo '4e6a0f828819e15d274ae58485585fc8b7caace0  ruby-2.3.6.tar.gz' | shasum -c - && \
# tar xzf ruby-2.3.6.tar.gz
# cd ruby-2.3.6
# ./configure --disable-install-rdoc
# make
# make install


# install re2
# git clone https://code.googlesource.com/re2
# cd re2
# make
# make test
# make install


# install gems
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
gem install bundler --no-ri --no-rdoc
# --version '1.14.6' 
gem install charlock_holmes --version $VERSION_CHARLOCK_HOLMES
unset HTTP_PROXY

#install yarn
sudo apt-get -y install apt-transport-https
curl --silent --show-error https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get -y update
sudo apt-get -y install yarn
   
