#!/bin/bash -ex

source /usr/local/src/gitlab.conf

echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "############### 10ruby #################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


# update ruby

apt-get install -y ruby ruby2.3-dev
apt-get clean all
sed -i '/ftp.us.debian.org\/debian testing main contrib non-free/d' /etc/apt/sources.list
cat /etc/apt/sources.list
apt-get update

# install gems
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
gem install bundler --no-ri --no-rdoc
# --version '1.14.6' 
gem install charlock_holmes --version $VERSION_CHARLOCK_HOLMES
unset HTTP_PROXY

#install yarn
sudo apt-get -y install apt-transport-https
curl --silent --show-error https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get -y update
sudo apt-get -y install yarn
   
