#!/bin/bash -ex

source /usr/local/src/gitlab.conf

echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "################# 15go #################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


# update go
rm -rf /usr/local/go
# curl --remote-name --progress https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz
curl --remote-name --progress http://192.168.200.143/_removeit/go1.8.3.linux-amd64.tar.gz
echo '1862f4c3d3907e59b04a757cfda0ea7aa9ef39274af99a784f5be843c80c6772  go1.8.3.linux-amd64.tar.gz' | shasum -a256 -c - && \
  tar -C /usr/local -xzf go1.8.3.linux-amd64.tar.gz
ln -sf /usr/local/go/bin/{go,godoc,gofmt} /usr/local/bin/
rm go1.8.3.linux-amd64.tar.gz

echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "############## 18nodeJS ################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1

# Install/UpdateNodeJS
curl --location https://deb.nodesource.com/setup_7.x | sudo bash -
apt-get -y install nodejs

curl --silent --show-error https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
apt-get -y update
apt-get -y install yarn
