#!/bin/bash -ex

source /usr/local/src/gitlab.conf

cat "########################################" >/dev/null 2>&1
cat "########################################" >/dev/null 2>&1
cat "########################################" >/dev/null 2>&1
cat "############## 18nodeJS ################" >/dev/null 2>&1
cat "########################################" >/dev/null 2>&1
cat "########################################" >/dev/null 2>&1
cat "########################################" >/dev/null 2>&1

# Install/UpdateNodeJS
curl --location https://deb.nodesource.com/setup_7.x | sudo bash -
apt-get -y install nodejs

curl --silent --show-error https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
apt-get -y update
apt-get -y install yarn

