#!/bin/bash -ex

source /usr/local/src/gitlab.conf

cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "############### 20users ################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt

# create user
adduser --disabled-login --gecos 'GitLab' $GIT_USER

# localhost keys will change on secret regeneration
exec_git "mkdir -p $GIT_HOME/.ssh"
exec_git "cat >$GIT_HOME/.ssh/config<<EOF
Host localhost
    Port 22
    StrictHostKeyChecking no
EOF"

# set gitlab's git name and email
exec_git "git config --global user.name GitLab"
exec_git "git config --global user.email $ADMIN_MAIL"
exec_git "git config --global core.autocrlf input"
exec_git "git config --global gc.auto 0"
exec_git "git config --global repack.writeBitmaps true"
exec_git "git config --global receive.advertisePushOptions true"
