#!/bin/bash -ex

source /usr/local/src/gitlab.conf


echo "########################################" >> log.txt
echo "########################################" >> log.txt
echo "########################################" >> log.txt
echo "############### 30shell ################" >> log.txt
echo "########################################" >> log.txt
echo "########################################" >> log.txt
echo "########################################" >> log.txt


# download and checkout specified version
URL="https://github.com/gitlabhq/gitlab-shell.git"

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
exec_git "git clone $URL $GIT_HOME/gitlab-shell"
unset HTTP_PROXY

cd $GIT_HOME/gitlab-shell
exec_git "git checkout $VERSION_GITLAB_SHELL"
exec_git "git checkout -b $VERSION_GITLAB_SHELL"
cat "*****************" > log.txt
cat "*****************" > log.txt
cat "*****************" > log.txt
cat "*****************" > log.txt
cat "***   $VERSION_GITLAB_SHELL  ***" > log.txt
exec_git "git rev-parse --abbrev-ref HEAD"
cat "*****************" > log.txt
cat "*****************" > log.txt
cat "*****************" > log.txt

# configure and install
exec_git "cp $GIT_HOME/gitlab-shell/config.yml.example \
             $GIT_HOME/gitlab-shell/config.yml"
exec_git "./bin/install"

