#!/bin/bash -ex

source /usr/local/src/gitlab.conf


echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "############# 40database ###############">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


#Install mysql
#sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5

#cat >/etc/apt/sources.list.d/mysql.list<<EOF
#deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7
#deb http://repo.mysql.com/apt/ubuntu/ trusty connector-python-2.1
#EOF

#apt-get -y update

#cat >/etc/apt/preferences<<EOF
#
#Package: mysql*
#Pin: origin "repo.mysql.com"
#Pin-Priority: 1001
#EOF

#/etc/init.d/mysql stop

#apt-cache policy mysql-server
#apt-get upgrade -y mysql-server mysql-client libmysqlclient-dev

/etc/init.d/mysql start
#mysql_upgrade --user=root --password=$MYSQL_PASS

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# create database and user
# $MYSQL_ADMIN create $DB_NAME --default-character-set=utf8;
$MYSQL_BATCH --execute "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
$MYSQL_BATCH --execute "CREATE DATABASE IF NOT EXISTS $DB_NAME DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
$MYSQL_BATCH --execute "SET default_storage_engine=INNODB;"
# $MYSQL_BATCH --execute "SET GLOBAL innodb_file_per_table=1, innodb_file_format=Barracuda, innodb_large_prefix=1;"
$MYSQL_BATCH --execute "SET GLOBAL innodb_file_per_table=1;"
$MYSQL_BATCH --execute "SET GLOBAL innodb_file_format = BARRACUDA;"
$MYSQL_BATCH --execute "SET GLOBAL innodb_large_prefix = ON;"
$MYSQL_BATCH --execute "SET GLOBAL log_bin_trust_function_creators = 1;"
# GRANT ALL PRIVILEGES ON gitlabhq_production.* TO 'git'@'localhost';
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to '$DB_USER'@localhost identified by '$DB_PASS'; flush privileges;"

cat >>/etc/mysql/my.cnf<<EOF

[mysqld]
default-storage-engine = innodb
log_bin_trust_function_creators = 1
innodb_file_format = Barracuda
innodb_large_prefix = 1
EOF

mysql --version
