#!/bin/bash -ex

source /usr/local/src/gitlab.conf


echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "############# 40database ###############">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# create database and user
$MYSQL_BATCH --execute "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
$MYSQL_BATCH --execute "CREATE DATABASE IF NOT EXISTS $DB_NAME DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
$MYSQL_BATCH --execute "SET default_storage_engine=INNODB;"
$MYSQL_BATCH --execute "SET GLOBAL innodb_file_per_table=1;"
$MYSQL_BATCH --execute "SET GLOBAL innodb_file_format = BARRACUDA;"
$MYSQL_BATCH --execute "SET GLOBAL innodb_large_prefix = ON;"
$MYSQL_BATCH --execute "SET GLOBAL log_bin_trust_function_creators = 1;"
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to '$DB_USER'@localhost identified by '$DB_PASS'; flush privileges;"
$MYSQL_BATCH --execute "show global variables like 'innodb%';"
$MYSQL_BATCH --execute "show global variables like 'innodb_file_format';"
$MYSQL_BATCH --execute "show global variables like 'innodb_file_per_table';"
$MYSQL_BATCH --execute "show global variables like 'innodb_lar%';"

cat >>/etc/mysql/my.cnf<<EOF

[mysqld]
default-storage-engine = innodb
log_bin_trust_function_creators = 1
innodb_file_format = Barracuda
innodb_file_per_table = 1
innodb_large_prefix = 1
EOF

mysql --version
