#!/bin/bash -ex

source /usr/local/src/gitlab.conf

cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "############# 55gitaly #################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt


# Install Gitaly
cd $GIT_HOME/gitaly
exec_git "git checkout $VERSION_GITALY_SERVER"
exec_git "git checkout -b $VERSION_GITALY_SERVER"
cat "*****************" > log.txt
cat "*****************" > log.txt
cat "*****************" > log.txt
cat "*****************" > log.txt
cat "***   $VERSION_GITALY_SERVER   ***" > log.txt
exec_git "git rev-parse --abbrev-ref HEAD"
cat "*****************" > log.txt
cat "*****************" > log.txt
cat "*****************" > log.txt
cd $GIT_HOME


# Fetch Gitaly source with Git and compile with Go
exec_git "bundle exec rake \"gitlab:gitaly:install[$GIT_HOME/gitaly]\" RAILS_ENV=production"

# Restrict Gitaly socket access
sudo chmod 0700 $GIT_HOME/gitlab/tmp/sockets/private
sudo chown $GIT_USER $GIT_HOME/gitlab/tmp/sockets/private
