#!/bin/bash -ex

source /usr/local/src/gitlab.conf

echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "############## 58nginx #################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


# install nginx
wget http://nginx.org/keys/nginx_signing.key
apt-key add nginx_signing.key

sh -c "cat >>/etc/apt/sources.list.d/sources.list<<EOF

deb http://nginx.org/packages/mainline/debian/ jessie nginx
deb-src http://nginx.org/packages/mainline/debian/ jessie nginx
EOF"

apt-get -y remove nginx-full nginx nginx-common
apt-get -y update
apt-get -y install nginx-full
