#!/bin/bash -ex

source /usr/local/src/gitlab.conf

cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "############ 60webserver ###############" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt


# setup unicorn and nginx
cd $GIT_HOME/gitlab/config
mv unicorn.rb.example unicorn.rb
sed -i '/gitlab.socket/ s/$/, :umask => 007/' unicorn.rb

cp initializers/rack_attack.rb.example initializers/rack_attack.rb
cp lib/support/logrotate/gitlab /etc/logrotate.d/gitlab

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/gitlab /etc/nginx/sites-enabled/gitlab

usermod -a -G git www-data

