#!/bin/bash -ex

source /usr/local/src/gitlab.conf

echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "############ 60webserver ###############">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


# setup unicorn and nginx
cd $GIT_HOME/gitlab/config
mv unicorn.rb.example unicorn.rb
sed -i '/gitlab.socket/ s/$/, :umask => 007/' unicorn.rb

cp initializers/rack_attack.rb.example initializers/rack_attack.rb
cp $GIT_HOME/gitlab/lib/support/logrotate/gitlab /etc/logrotate.d/gitlab

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/gitlab /etc/nginx/sites-enabled/gitlab

usermod -a -G git www-data

