#!/bin/bash -ex

source /usr/local/src/gitlab.conf

cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "############ 70initscript ##############" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt
cat "########################################" >> log.txt

cp /home/git/gitlab/lib/support/init.d/gitlab /etc/init.d/gitlab
chown root:root /etc/init.d/gitlab

update-rc.d gitlab defaults
update-rc.d gitlab enable

