#!/bin/bash -ex

source /usr/local/src/gitlab.conf

echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "############ 70initscript ##############">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1

cp /home/git/gitlab/lib/support/init.d/gitlab /etc/init.d/gitlab
chown root:root /etc/init.d/gitlab

update-rc.d gitlab defaults
update-rc.d gitlab enable

