#!/bin/bash -ex

source /usr/local/src/gitlab.conf

echo "########################################" >> log.txt
echo "########################################" >> log.txt
echo "########################################" >> log.txt
echo "############ 70initscript ##############" >> log.txt
echo "########################################" >> log.txt
echo "########################################" >> log.txt
echo "########################################" >> log.txt

cp /home/git/gitlab/lib/support/init.d/gitlab /etc/init.d/gitlab
chown root:root /etc/init.d/gitlab

update-rc.d gitlab defaults
update-rc.d gitlab enable

