#!/bin/bash -ex

source /usr/local/src/gitlab.conf

echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "################ 80redis ###############">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


# make Redis listen on Unix socket
echo 'include /etc/redis/unixsocket.conf' >> /etc/redis/redis.conf

# allow git to use redis' socket
usermod -a -G redis $GIT_USER

for i in development test production; do
    echo "$i: unix:/var/run/redis/redis.sock" >> /home/git/gitlab/config/resque.yml
done

