#!/bin/bash -ex

source /usr/local/src/gitlab.conf

service redis-server start
exec_git "cd ~/gitlab && RAILS_ENV=production bin/background_jobs start"
exec_git "bundle exec rake gitlab:assets:compile RAILS_ENV=production NODE_ENV=production"
exec_git "RAILS_ENV=production bundle exec rake assets:precompile webpack:compile"
exec_git "bundle exec rake gitlab:check RAILS_ENV=production"
service redis-server stop

# cleanup
rm -rf $SRC/*

