#!/bin/bash -ex

source /usr/local/src/gitlab.conf

echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "################ 90finish ##############">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1
echo "########################################">/dev/null 2>&1


cd $GIT_HOME/gitlab


update-rc.d gitlab defaults
update-rc.d gitlab enable

service ssh start
service redis-server start
service nginx start
service mysql start
service gitlab start

exec_git "cd ~/gitlab && RAILS_ENV=production bin/background_jobs start"
exec_git "bundle exec rake gitlab:assets:compile RAILS_ENV=production NODE_ENV=production"
exec_git "RAILS_ENV=production bundle exec rake assets:precompile webpack:compile"

## TESTING
exec_git "bundle exec rake gitlab:check RAILS_ENV=production"
service ssh stop
service redis-server stop
service nginx stop
service mysql stop
service gitlab stop

# cleanup
rm -rf $SRC/*

